### ISSUE TITLE
Opening from right click > NotepadCode sometimes results in crash

### ISSUE THREAD

**Issue by michael-reuter** [kmccarthy55/NotepadCode#13] opened 2019-07-18 16:56 UTC
![image](https://user-images.githubusercontent.com/17342888/61476600-08692900-a953-11e9-9219-b6bc4b88fdf4.png)

**Comment by michael-reuter** [comment] 2019-07-18 17:01
This appears to be caused by the .CCL (capital) extension.

**Comment by kmccarthy55** [comment] 2019-07-18 17:11
As of right now the issue is with any extension that is Capital so as of right now you can click continue and it will still allow the application to open with the file it just won't auto select the language.

**Comment by kmccarthy55** [comment] 2019-07-24 18:14
This has been fixed in 1.0.6.0 code

**Closed as completed by kmccarthy55** 2019-07-24 18:14 UTC
Labels: bug
